- name: Generate SSH key on control node
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Generate SSH key
      openssh_keypair:
        path: /tmp/logornerkeys
        type: rsa
        size: 4096
        state: present
        force: no
